version: '3'

services:
  redis:
    image: redis
    restart: always
    container_name: redis-conf
    ports:
      - "6379:6379"
  
  mysql:
    image : mysql:5.7
    restart: always
    container_name: mysql-conf
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
        - ./db/db.sql:/data/application/init.sql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: config
      MYSQL_ROOT_PASSWORD: root
